# Generated by Django 4.1.7 on 2023-08-02 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_category_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='image',
        ),
    ]
